# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchImage' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SearchImage
    pod 'Alamofire', '~> 5.2'
    pod 'Then'

  target 'SearchImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SearchImageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
